language: android
jdk: oraclejdk8
sudo: true
env:
  global:
     - ANDROID_API_LEVEL=25
     - ADB_INSTALL_TIMEOUT=10
     - ANDROID_BUILD_TOOLS_VERSION=25.0.3

android:
  components:
     - tools
     - tools
     - platform-tools
     - build-tools-$ANDROID_BUILD_TOOLS_VERSION
     - android-$ANDROID_API_LEVEL
     # Google Play Services
     - extra-google-google_play_services
     # Support librar
     - extra-android-support
     - extra-google-android-support
     # Latest artifacts in local repository
     - extra-google-m2repository
     - extra-android-m2repository
     - sys-img-armeabi-v7a-android-24
  licenses:
     - 'android-sdk-preview-license-52d11cd2'
     - 'android-sdk-license-.+'
     - 'google-gdk-license-.+'
     - '.+'

before_script:
  - android list targets # list pre-installed targets # <---- list all installed targets
  - android list sdk --no-ui --all --extended | grep -E '^id:' | awk -F '"' '{$1=""; print $2}' # <---- list all available components
  - echo "Travis branch is $TRAVIS_BRANCH"
  - echo "Travis branch is in pull request $TRAVIS_PULL_REQUEST"

script:
  - echo no | android create avd --force --name test --target android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window -gpu off &
  - android-wait-for-emulator
  - "./gradlew build connectedCheck --stacktrace"
before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
after_failure: "cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"