language: android
jdk: oraclejdk8
sudo: true
env:
  global:
  - ANDROID_API_LEVEL=25
  - ADB_INSTALL_TIMEOUT=10
  - ANDROID_BUILD_TOOLS_VERSION=25.0.3
  - secure: YhjJXpnxBywrx32UEefjGbBq4LztT7aJuYYXQlwK24GBCkJ1OgC2nlkDQM5anBDdD5cRIB229rnfLk4eXJzwLZ3ghUf+mIAdl7txzz9VOx3ZjG38J8KJJj8DGyWA295pRHg6/Tr/Y3QUeYtAbPttVWwBGqsD+FjVgoiKyp/fTWGckNJvDXoji02pF0jyklAtxKRW2OkKFuho2ZDUN1wFMXsCOTay1PB4eM/gj15zJmFvLcyFT5I5lesNLV61KXFhymR73RBvB899auD3kdmz8QmgcDabzjSLdGiCUqmNUaHLJjIYV6MbEuM/efexIFxOHhfM2nyYZ1u1u6Y5bWwsfC2E3VdtDDrzaNjKFVHYUa9XyQURCixaBU4ABW6FdqqcD9nw6OeXJSd+kIedE78lUHPw++SuuEVWBxx2QXHgS1wEcwxWbtFtudsUxSJaD64t4OCUi9JM2soxE3HrtRxUBXlBHjLxmZ8OEuJLq8oanBXrIlBSVh4jVdWiMXMqy2nDZPxPzdPFZB5Z3LT2iVvHzndibeZ6sOhNu6g3987LvJKdLqB+7TPeRr4ZVo28+5kbkI3DlhbqY0oYNqfzxDBwpC5D87MVpS026UmdnzqZH3oR///nyAhYPN7wvy4N3svoIvQ6hqrYx+HyS7T/qmYhg3GLfp0Tl0O3I7WLw7tatpM=
  - secure: Cr4Dikwg4SQjQcb+ntbJr1BEPmyRkgqJtFkH7d7BVyJu8dm8tUrU8y1+Owi8sg8CfmCHQFQC6Jb4Lu80XhBW2XQ8xWd+9HO7+CjvO/Fv8k7yc+thDXeTp1MGFkTZl9KNBy8/jE5F4l8YisJoYLa4snsxtshNKOLnBfX9SFaXYSmFWu17EzmWvNwKxokq9qhtu/M/639k35U0vkigF7MLubnHkGkth7pwHIbb2ovi8BPPLNFtrhgN+qIE4s4zZKwFr0ECshAFOFAKLOWnU9EPeA0VfgD9Y7pQhU0IxvF1ytLolyVNDgUWIPZB2ed7uqew2e1U/wIDTNnFRyxEyrwzab8aBzDaDnYvx54/tpdNEvO63BaaA6ZPQoMl8uAqhwEVc2cDzI+ZnbyGJHEDsbR7wYdu1fdh//AyCseba5N8uR6HajVMgtaij5P7i3NRnPEeLeTWNStpIxkHt1yRbpXdkBJnftxzml1uDNlY7jdcW9i464vkmuFkFxjgbCnzLsXBrGx1zdCTukT9xNunKlpicTVz6Wj6c3r4D6avRegfha10iRKZTZB9bCJA5nZ2fxdZ98/oa0zOe6MtKPa0Z9ml7wHkJF8h8PD+/je8ALwI5pp2kemeTjz+B3QGYcinYer3iGOb0nnT2r0ZmmGKbfuxUsqRQZg0B6RYh1N718j93mI=
android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - android-$ANDROID_API_LEVEL
  - extra-google-google_play_services
  - extra-android-support
  - extra-google-android-support
  - extra-google-m2repository
  - extra-android-m2repository
  - sys-img-armeabi-v7a-android-24
  licenses:
  - android-sdk-preview-license-52d11cd2
  - android-sdk-license-.+
  - google-gdk-license-.+
  - ".+"
before_install:
- openssl aes-256-cbc -K $encrypted_ea87b50d7927_key -iv $encrypted_ea87b50d7927_iv -in keystore2.jks.enc -out keystore2.jks -d
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
- chmod +x gradlew
- "./gradlew dependencies || true"
before_script:
- android list targets
- android list sdk --no-ui --all --extended | grep -E '^id:' | awk -F '"' '{$1="";
  print $2}'
- echo "Travis branch is $TRAVIS_BRANCH"
- echo "Travis branch is in pull request $TRAVIS_PULL_REQUEST"
- echo no | android create avd --force --name test --target android-21 --abi armeabi-v7a
- emulator -avd test -no-skin -no-audio -no-window -gpu off &
- android-wait-for-emulator
script:
- "./gradlew clean build connectedCheck -PdisablePreDex --stacktrace"
before_deploy:
- cp $TRAVIS_BUILD_DIR/.keystore $HOME
- cd app/build/outputs/apk/
- jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $HOME/keystore2.jks
  -storepass $storepass -keypass $keypass app-release-unsigned.apk DicomFlowKey
- jarsigner -verify app-release-unsigned.apk
- "${ANDROID_HOME}/build-tools/25.0.3/zipalign -v 4 app-release-unsigned.apk dicomAndroidClient.apk"
deploy:
  provider: releases
  file: dicomAndroidClient.apk
  skip_cleanup: true
  on:
    repo: DicomFlow/dicomAndroidClient
    tags: true
    jdk: oraclejdk8
  api_key:
    secure: c4x2pUbTcW/cP5wYlPDH9xoqUhr82Nisic/amZnI4ym01S+1KQLR7lNAQUQcrmqerO0oA9CHjPZjGsiWituY6kC7d/vZBEAmlTqOtknke8rNCug9re2oIbuTrMx5YLGssPTnVKmIgvsWnqDg1dpRBzE5cOJT+g8Ynrq4exxLCeNqXrSnaaB79quKXgiznlCObxpJk2MOMx7+Ap+dRCWK9xAMJgJ/ylWrpLZ0PP1H+P8fDl5r3MDRmyRJwq2sdye8i4UOsNrbga9nDSD33WB2BVuRkBYOITUSpRLoBU2yE5N9nMpdJ580LHU6A9pPQx4+HHKIuKoFC1Bhn86EK7kq8xqBku2nFjp/AMip6XWYzhw8BQi/3WZ3QyaJqzj0ZUO/MgTgTNWqLrjeRPwrjZbUXZqakAPVaHZQrwkGEgcVS5E7lmscPj6ZVCWgH4i6MesEbqkWxdVjZP37FwxV/wVbWJ60o6AR5cGE1y0SYhLD9TgWUIc3f7U0o9cKgw3raIjsIJdS9gaxO73ZX2Xy0QDk9p6FE1HaCusntZ5XNICn/SOFGFvWx+NMAGAp941/9h3Q+QOEz13eHF2JWKCEO1h/r/yXBW4jbxoMkxk2FDPWPy/bN7npT38Gh4EY4Frcf+hGeGWds2k7G9QCBI/CU4ryXJodRgpiZuRJb6BLYHsUdis=
after_failure: cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml
